export const ADD_COMPONENT = 'ADD_COMPONENT'
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT'
export const SET_SELECTED_COMPONENT_ID = 'SET_SELECTED_COMPONENT_ID'
export const TRIGGER_UPDATE = 'TRIGGER_UPDATE'
