export const COUPON_SET_ALL_USERS = 'COUPON_SET_ALL_USERS'
export const COUPON_SET_ALL_SHOPS = 'COUPON_SET_ALL_SHOPS'
export const COUPON_SET_ALL_CATEGORIES = 'COUPON_SET_ALL_CATEGORIES'

export const COUPON_SET_INCLUDED_USERS = 'COUPON_SET_INCLUDED_USERS'
export const COUPON_SET_EXCLUDED_USERS = 'COUPON_SET_EXCLUDED_USERS'

export const COUPON_SET_INCLUDED_SHOPS = 'COUPON_SET_INCLUDED_SHOPS'
export const COUPON_SET_EXCLUDED_SHOPS = 'COUPON_SET_EXCLUDED_SHOPS'

export const COUPON_SET_INCLUDED_CATEGORIES = 'COUPON_SET_INCLUDED_CATEGORIES'
export const COUPON_SET_EXCLUDED_CATEGORIES = 'COUPON_SET_EXCLUDED_CATEGORIES'
